# 1. Read the dataset, show its head, shape and description

In [1]:
import pandas as pd

df1 = pd.read_csv('ml_python_labexam_2023_09_11.csv',sep=';')

In [2]:
df1.head()

,Date,Time,X00,X01,X02,X03,X04,X05,X06,X07,X08,X09,X10,X11,X12,X13,X14,X15
0,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,NaN,NaN,NaN
1,10/03/2004,19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,NaN,NaN,NaN
2,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,NaN,NaN,NaN
3,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,NaN,NaN,NaN
4,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,NaN,NaN,NaN

In [3]:
print(f"Dataset has {df1.shape[0]} entries and {df1.shape[1]} columns")

Dataset has 9471 entries and 18 columns

In [4]:
df1.describe()

,X00,X01,X02,X03,X04,X05,X06,X07,X08,X09,X10,X11,X12,X13,X14,X15
count,7765.000000,8991.000000,914.000000,9357.000000,8991.000000,7718.000000,8991.000000,7715.000000,8991.000000,8991.000000,8991.000000,8991.000000,8991.000000,0.0,0.0,0.0
mean,2.127521,1099.833166,218.811816,9.688704,939.153376,246.896735,835.493605,113.091251,1456.264598,1022.906128,18.317829,49.234201,1.025530,NaN,NaN,NaN
std,1.463171,217.080037,204.459921,7.559785,266.831429,212.979168,256.817320,48.370108,346.206794,398.484288,8.832116,17.316892,0.403813,NaN,NaN,NaN
min,0.000000,647.000000,7.000000,0.000000,383.000000,2.000000,322.000000,2.000000,551.000000,221.000000,-1.900000,9.200000,0.184700,NaN,NaN,NaN
25%,1.000000,937.000000,67.000000,4.000000,734.500000,98.000000,658.000000,78.000000,1227.000000,731.500000,11.800000,35.800000,0.736800,NaN,NaN,NaN
50%,1.800000,1063.000000,150.000000,7.900000,909.000000,180.000000,806.000000,109.000000,1463.000000,963.000000,17.800000,49.600000,0.995400,NaN,NaN,NaN
75%,2.900000,1231.000000,297.000000,13.600000,1116.000000,326.000000,969.500000,142.000000,1674.000000,1273.500000,24.400000,62.500000,1.313700,NaN,NaN,NaN
max,11.900000,2040.000000,1189.000000,63.700000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000,44.600000,88.700000,2.231000,NaN,NaN,NaN

# 2. Eliminate totally null columns and totally null rows, eliminate columns with less than 1/3 of non null values; ﬁll the remaining NaN values with the mean of the column

In [5]:
pd.isnull(df1)

,Date,Time,X00,X01,X02,X03,X04,X05,X06,X07,X08,X09,X10,X11,X12,X13,X14,X15
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9466,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9467,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9468,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9469,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9470,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [6]:
#len(pd.isnull(df['X00']))
pd.isnull(df1['X00']).value_counts(df1.count)[True]

np.float64(0.18012881427515573)

In [7]:
# eliminating columns which are more than 2/3 null values
df2 = df1.copy()
for col in df1.columns:
    if pd.isnull(df1[col]).value_counts(df1.count)[True] >= 0.67:
        df2 = df2.drop(columns=[col])

In [8]:
df2

,Date,Time,X00,X01,X03,X04,X05,X06,X07,X08,X09,X10,X11,X12
0,10/03/2004,18.00.00,2.6,1360.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,10/03/2004,19.00.00,2.0,1292.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,10/03/2004,20.00.00,2.2,1402.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,10/03/2004,21.00.00,2.2,1376.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,10/03/2004,22.00.00,1.6,1272.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df2 = df2.dropna()

In [10]:
df2.isna().value_counts()

Date   Time   X00    X01    X03    X04    X05    X06    X07    X08    X09    X10    X11    X12
False  False  False  False  False  False  False  False  False  False  False  False  False  False    7024
Name: count, dtype: int64

# 3. Drop Time, convert Date from string to datetime and group by Date using mean as aggregate  function

In [11]:
df3 = df2.drop(columns=['Time'])

In [12]:
df3['Date'] = pd.to_datetime(df3['Date'],format='mixed')

In [13]:
df3['Date']

0      2004-10-03
1      2004-10-03
2      2004-10-03
3      2004-10-03
4      2004-10-03
          ...
9352   2005-04-04
9353   2005-04-04
9354   2005-04-04
9355   2005-04-04
9356   2005-04-04
Name: Date, Length: 7024, dtype: datetime64[us]

In [14]:
df = df3.groupby(['Date']).mean()

In [15]:
df

,X00,X01,X03,X04,X05,X06,X07,X08,X09,X10,X11,X12
Date,,,,,,,,,,,,
2004-01-04,2.720000,1258.800000,12.370000,1025.300000,168.600000,869.750000,98.950000,1655.500000,1171.200000,15.845000,50.035000,0.855655
2004-01-05,2.090909,1111.318182,9.004545,928.136364,107.909091,906.818182,86.909091,1647.681818,913.636364,20.531818,50.427273,1.156805
2004-01-06,2.100000,1203.800000,14.485000,1113.200000,172.300000,799.250000,83.600000,1966.350000,1181.900000,20.820000,64.170000,1.532655
2004-01-07,2.230435,1142.869565,12.634783,1055.782609,139.695652,726.217391,113.434783,1868.086957,1077.260870,30.630435,39.208696,1.620557
2004-01-08,1.004348,977.782609,5.904348,797.000000,51.739130,877.434783,58.521739,1559.260870,672.391304,30.908696,41.400000,1.667635
...,...,...,...,...,...,...,...,...,...,...,...,...
2005-11-02,3.866667,1470.666667,14.133333,1119.000000,487.333333,510.666667,204.000000,1315.666667,2043.666667,7.966667,54.100000,0.579733
2005-11-03,1.552174,1170.260870,10.365217,955.260870,360.478261,671.130435,156.173913,1195.173913,1216.869565,11.060870,44.769565,0.578513
2005-12-01,3.372727,1328.318182,16.340909,1173.090909,577.136364,533.545455,151.863636,1519.954545,1496.000000,12.045455,65.318182,0.903855
2005-12-02,3.400000,1493.739130,15.617391,1152.565217,583.304348,508.913043,215.478261,1382.695652,1917.913043,8.460870,58.839130,0.651178
2005-12-03,0.616667,1116.625000,5.641667,779.208333,239.125000,722.916667,130.041667,1147.291667,792.875000,13.083333,52.312500,0.764592

# 4. Preparation of the boolean matrix 
• Discretise continuous values with two bins, kmeans strategy and onehot-dense encoding

• Discretization/encoding generates 0/1 values; convert the binary values obtained into boolean, as requested by Apriori

In [16]:
from sklearn.preprocessing import KBinsDiscretizer
kb = KBinsDiscretizer(n_bins=2,encode='onehot-dense', strategy='kmeans')
transformed_data = kb.fit_transform(df)

In [17]:
transformed_data

array([[0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 1.],
       ...,
       [0., 1., 0., ..., 1., 1., 0.],
       [0., 1., 0., ..., 1., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]], shape=(341, 24))

# 5. Set the names of two columns generated by the discretisation of each attribute A to A_low, A_high (with discretisation/one-hot-encoding, each original column generates two columns, the ﬁrst is for the low values, the second for the high values)

In [18]:
new_cols = pd.Index(kb.get_feature_names_out()).str.replace('_0.0','_low').str.replace('_1.0','_high')
new_cols

Index(['X00_low', 'X00_high', 'X01_low', 'X01_high', 'X03_low', 'X03_high',
       'X04_low', 'X04_high', 'X05_low', 'X05_high', 'X06_low', 'X06_high',
       'X07_low', 'X07_high', 'X08_low', 'X08_high', 'X09_low', 'X09_high',
       'X10_low', 'X10_high', 'X11_low', 'X11_high', 'X12_low', 'X12_high'],
      dtype='str')

In [19]:
transformed_data.astype(bool)

array([[False,  True, False, ..., False,  True, False],
       [ True, False,  True, ..., False, False,  True],
       [ True, False, False, ...,  True, False,  True],
       ...,
       [False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False],
       [ True, False,  True, ...,  True,  True, False]], shape=(341, 24))

In [20]:
df_ = pd.DataFrame(transformed_data.astype(bool), columns=new_cols)

In [21]:
df_

,X00_low,X00_high,X01_low,X01_high,X03_low,X03_high,X04_low,X04_high,X05_low,X05_high,...,X08_low,X08_high,X09_low,X09_high,X10_low,X10_high,X11_low,X11_high,X12_low,X12_high
0,False,True,False,True,False,True,False,True,True,False,...,False,True,False,True,True,False,True,False,True,False
1,True,False,True,False,True,False,True,False,True,False,...,False,True,True,False,False,True,True,False,False,True
2,True,False,False,True,False,True,False,True,True,False,...,False,True,False,True,False,True,False,True,False,True
3,False,True,False,True,False,True,False,True,True,False,...,False,True,True,False,False,True,True,False,False,True
4,True,False,True,False,True,False,True,False,True,False,...,False,True,True,False,False,True,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,False,True,False,True,False,True,False,True,False,True,...,True,False,False,True,True,False,False,True,True,False
337,True,False,False,True,True,False,False,True,False,True,...,True,False,False,True,True,False,True,False,True,False
338,False,True,False,True,False,True,False,True,False,True,...,False,True,False,True,True,False,False,True,True,False
339,False,True,False,True,False,True,False,True,False,True,...,True,False,False,True,True,False,False,True,True,False
340,True,False,True,False,True,False,True,False,True,False,...,True,False,True,False,True,False,False,True,True,False

# 6. ﬁnd a value of min_support such that the Apriori algorithm generates at least 8 frequent itemsets with at least 2 items, output the result

In [38]:
from mlxtend.frequent_patterns import apriori
min_sup = 0.4
target_itemset = 8
while True:
    frequent_itemsets = apriori(df_, min_support=min_sup, use_colnames=True)
    frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(len)
    n_multi = (frequent_itemsets['length']>=2).sum()
    if n_multi >= target_itemset:
        break
    min_sup-=0.01

print(f"min support: {min_sup:.2f}, number of itemsets with at least 2 items: {n_multi}")

min support: 0.40, number of itemsets with at least 2 items: 53

# 7. ﬁnd the minimum metric threshold such that at least 100 association rules are extracted from the frequent itemsets found and show the metrics used and the best 10 rules by descending conﬁdence and support

In [39]:
from mlxtend.frequent_patterns import association_rules
min_thres = 0.9
target_rules = 100
while True:
    rules = association_rules(frequent_itemsets, metric='confidence',min_threshold=min_thres)
    if len(rules) >= target_rules:
        break
    min_thres-=0.01

In [40]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({X00_low}),frozenset({X01_low}),0.501466,0.586510,0.454545,0.906433,1.545468,1.0,0.160430,4.419172,0.707970,0.717593,0.773713,0.840716
1,frozenset({X04_low}),frozenset({X00_low}),0.483871,0.501466,0.428152,0.884848,1.764522,1.0,0.185508,4.329372,0.839469,0.768421,0.769020,0.869325
2,frozenset({X00_low}),frozenset({X05_low}),0.501466,0.653959,0.451613,0.900585,1.377127,1.0,0.123675,3.480766,0.549312,0.641667,0.712707,0.795584
3,frozenset({X00_low}),frozenset({X09_low}),0.501466,0.548387,0.442815,0.883041,1.610251,1.0,0.167818,3.861290,0.760187,0.729469,0.741019,0.845264
4,frozenset({X00_high}),frozenset({X04_high}),0.498534,0.516129,0.442815,0.888235,1.720956,1.0,0.185508,4.329372,0.835405,0.774359,0.769020,0.873095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,"frozenset({X03_low, X09_low, X04_low})",frozenset({X05_low}),0.439883,0.653959,0.401760,0.913333,1.396622,1.0,0.114094,3.992781,0.507013,0.580508,0.749548,0.763842
102,"frozenset({X05_low, X03_low})","frozenset({X09_low, X04_low})",0.434018,0.439883,0.401760,0.925676,2.104369,1.0,0.210843,7.536124,0.927234,0.850932,0.867306,0.919505
103,"frozenset({X05_low, X04_low})","frozenset({X03_low, X09_low})",0.416422,0.451613,0.401760,0.964789,2.136318,1.0,0.213698,15.574194,0.911455,0.861635,0.935791,0.927200
104,"frozenset({X03_low, X09_low})","frozenset({X05_low, X04_low})",0.451613,0.416422,0.401760,0.889610,2.136318,1.0,0.213698,5.286528,0.969944,0.861635,0.810840,0.927200
105,"frozenset({X09_low, X04_low})","frozenset({X05_low, X03_low})",0.439883,0.434018,0.401760,0.913333,2.104369,1.0,0.210843,6.530566,0.936943,0.850932,0.846874,0.919505

In [41]:
print(f" min threshold: {min_thres:.2f}, number of rules: {len(rules)}")

 min threshold: 0.88, number of rules: 106

In [42]:
rules.sort_values(['confidence','support'],ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
12,frozenset({X03_high}),frozenset({X04_high}),0.489736,0.516129,0.489736,1.0,1.93750,1.0,0.236969,inf,0.948276,0.948864,1.0,0.974432
9,frozenset({X04_low}),frozenset({X03_low}),0.483871,0.510264,0.483871,1.0,1.95977,1.0,0.236969,inf,0.948864,0.948276,1.0,0.974138
57,"frozenset({X09_low, X04_low})",frozenset({X03_low}),0.439883,0.510264,0.439883,1.0,1.95977,1.0,0.215426,inf,0.874346,0.862069,1.0,0.931034
42,"frozenset({X01_low, X04_low})",frozenset({X03_low}),0.431085,0.510264,0.431085,1.0,1.95977,1.0,0.211118,inf,0.860825,0.844828,1.0,0.922414
30,"frozenset({X04_low, X00_low})",frozenset({X03_low}),0.428152,0.510264,0.428152,1.0,1.95977,1.0,0.209682,inf,0.856410,0.839080,1.0,0.919540
41,"frozenset({X00_high, X03_high})",frozenset({X04_high}),0.428152,0.516129,0.428152,1.0,1.93750,1.0,0.207171,inf,0.846154,0.829545,1.0,0.914773
62,"frozenset({X06_low, X03_high})",frozenset({X04_high}),0.422287,0.516129,0.422287,1.0,1.93750,1.0,0.204333,inf,0.837563,0.818182,1.0,0.909091
54,"frozenset({X05_low, X04_low})",frozenset({X03_low}),0.416422,0.510264,0.416422,1.0,1.95977,1.0,0.203937,inf,0.839196,0.816092,1.0,0.908046
91,"frozenset({X01_low, X09_low, X04_low})",frozenset({X03_low}),0.413490,0.510264,0.413490,1.0,1.95977,1.0,0.202501,inf,0.835000,0.810345,1.0,0.905172
66,"frozenset({X01_low, X04_low, X00_low})",frozenset({X03_low}),0.404692,0.510264,0.404692,1.0,1.95977,1.0,0.198192,inf,0.822660,0.793103,1.0,0.896552